### PR TITLE
Local arki-server for test suite

### PR DESCRIPTION
**Pull request by edigiacomo**
Local arki-server for test suites and arki-mergeconf test (related issue: #104).

### CODE REVIEW

**Comment by spanezz** [comment]
I'm merging. When I'll eventually run unit tests on my system, I'll see how to replace that `sleep 10` with something that doesn't delay tests for that long, even when run on a slow system

**Comment by edigiacomo** [comment]
Something like:

```
diff --git a/src/testlib.sh b/src/testlib.sh
index c3e768f..a73e1bc 100755
--- a/src/testlib.sh
+++ b/src/testlib.sh
@@ -70,9 +70,14 @@ setup() {
 
 runserver()
 {
-    arki-server -p 7117 --url=http://localhost:7117 --quiet --accesslog=access.log --errorlog=error.log conf &
-    sleep 10
+    local count=0
+    arki-server -p 7117 --url=$SERVER_URL --quiet --accesslog=access.log --errorlog=error.log conf &
     echo $! > arki-server.pid
+    for count in {1..30}
+    do
+        curl $SERVER_URL &>/dev/null && break
+        sleep 1
+    done
 }
 
 ## Call at end of the test script
```

**Comment by spanezz** [comment]
Looks good, possibly with a `sleep 0.2` instead of `sleep 1`, for machines where arki-server starts in less than one second

**Comment by edigiacomo** [comment]
Yes, I always forget that `sleep` support floating point numbers :)

**Comment by edigiacomo** [comment]
Yes, I always forget that `sleep` support floating point numbers :)

**Comment by edigiacomo** [comment]
See f3a1d770c1e72ed773b2b7de98e34fd8b9aa84b9

**Pull request merged**
